name: global_refresh
description: Simple library for refreshing the main state of an application
version: 1.0.0
repository: https://github.com/landamessenger/global-refresh.git

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
